name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  DeployToGitHubPages:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Get Artifact
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: ./README.md

      - name: Get GitPahes repository
        uses: actions/checkout@v4
        with:
          name: OrangeAlertX/OrangeAlertx.github.io
          toket: ${{ secrets.TOKEN_GITHUB_PAGES }}

      - name: Delete previous version
        run: rm -rf ./*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: README
          path: ./

      - name: Push to GitHub Actions
        run: |
          git add --all && git commit -m 'autosync'
          git remote remove origin
          git remote add origin https://${{ secrets.TOKEN_GITHUB_PAGES }}@github.com/OrangeAlertX/OrangeAlertx.github.io
          git config user.email "orangealertx@gmail.com"
          git config user.name "bogdan_sevruk"
          git push origin main
