name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  GetNewVersion:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Get Artifact
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: ./README.md
  DeployToGitHubPages:
    runs-on: ubuntu-latest
    needs: GetNewVersion

    steps:
      - name: set git
        run: |
          git init --initial-branch=main
          git config user.email "orangealertx@gmail.com"
          git config user.name "bogdan_sevruk"

      - name: Set connection
        env: 
          TOKEN: ${{ secrets.TOKEN_GITHUB_PAGES }}
        run: git remote add origin https://$TOKEN@github.com/OrangeAlertX/OrangeAlertx.github.io

      - name: pull
        run: |
          git pull origin main
          git rev-parse --abbrev-ref HEAD

      - name: Clear current version
        run: rm -rf ./*
      
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: README
          path: ./

      - name: Push to GitHub Actions - local commit
        run: |
          git add --all
          git commit -m 'autosync'

      - name: Deploy
        run: git push origin main
